# Generated by Django 5.1.2 on 2025-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0055_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_host',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
