# Generated by Django 5.1.2 on 2025-09-24 01:02

import concurrency.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0057_remove_botevent_valid_event_type_event_sub_type_combinations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdeliveryattempt',
            name='webhook_trigger_type',
            field=models.IntegerField(choices=[(1, 'Bot State Change'), (2, 'Transcript Update'), (3, 'Chat Messages Update'), (4, 'Participant Join/Leave'), (5, 'Calendar Events Update'), (6, 'Calendar State Change'), (7, 'Async Transcription State Change')], default=1),
        ),
        migrations.CreateModel(
            name='AsyncTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('state', models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Complete'), (4, 'Failed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(default=dict)),
                ('failure_data', models.JSONField(default=None, null=True)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='async_transcriptions', to='bots.recording')),
            ],
        ),
        migrations.AddField(
            model_name='utterance',
            name='async_transcription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='bots.asynctranscription'),
        ),
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_blob', models.BinaryField()),
                ('audio_format', models.IntegerField(choices=[(1, 'PCM'), (2, 'MP3')], default=1)),
                ('timestamp_ms', models.BigIntegerField()),
                ('duration_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_rate', models.IntegerField()),
                ('source', models.IntegerField(choices=[(1, 'Per Participant Audio'), (2, 'Mixed Audio')], default=1)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_chunks', to='bots.participant')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_chunks', to='bots.recording')),
            ],
        ),
        migrations.AddField(
            model_name='utterance',
            name='audio_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utterances', to='bots.audiochunk'),
        ),
    ]
