# Generated by Django 5.1.2 on 2025-09-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_organization_autopay_amount_to_purchase_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_async_transcription_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
